name: CI/CD Pipeline MLOps

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
    
    - name: Configuration Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Installation des dependances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Construction de l'image Docker
      run: |
        docker build -t mlops-loan-app:latest .
    
    - name: Test du conteneur Docker
      run: |
        docker run -d -p 8501:8501 --name test-container mlops-loan-app:latest
        sleep 15
        curl -f http://localhost:8501/_stcore/health || exit 1
        docker stop test-container
